# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\myGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class myGuiMainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 780)
        self.pushButtonStart = QtWidgets.QPushButton(Dialog)
        self.pushButtonStart.setGeometry(QtCore.QRect(40, 720, 85, 26))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.comboBoxProvince = QtWidgets.QComboBox(Dialog)
        self.comboBoxProvince.setGeometry(QtCore.QRect(40, 110, 78, 22))
        self.comboBoxProvince.setObjectName("comboBoxProvince")
        self.comboBoxCity = QtWidgets.QComboBox(Dialog)
        self.comboBoxCity.setGeometry(QtCore.QRect(140, 110, 78, 22))
        self.comboBoxCity.setObjectName("comboBoxCity")
        self.comboBoxDistrict = QtWidgets.QComboBox(Dialog)
        self.comboBoxDistrict.setGeometry(QtCore.QRect(240, 110, 121, 22))
        self.comboBoxDistrict.setObjectName("comboBoxDistrict")
        self.comboBoxSite = QtWidgets.QComboBox(Dialog)
        self.comboBoxSite.setGeometry(QtCore.QRect(380, 110, 231, 22))
        self.comboBoxSite.setObjectName("comboBoxSite")
        self.pushButtonSelectJsonFile = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectJsonFile.setGeometry(QtCore.QRect(40, 60, 85, 26))
        self.pushButtonSelectJsonFile.setObjectName("pushButtonSelectJsonFile")
        self.pushButtonSelectImgFile = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectImgFile.setGeometry(QtCore.QRect(40, 180, 85, 26))
        self.pushButtonSelectImgFile.setObjectName("pushButtonSelectImgFile")
        self.labelHelp1 = QtWidgets.QLabel(Dialog)
        self.labelHelp1.setGeometry(QtCore.QRect(40, 30, 251, 16))
        self.labelHelp1.setObjectName("labelHelp1")
        self.labelJsonFileName = QtWidgets.QLabel(Dialog)
        self.labelJsonFileName.setGeometry(QtCore.QRect(140, 60, 461, 16))
        self.labelJsonFileName.setObjectName("labelJsonFileName")
        self.labelHelp2 = QtWidgets.QLabel(Dialog)
        self.labelHelp2.setGeometry(QtCore.QRect(40, 150, 141, 16))
        self.labelHelp2.setObjectName("labelHelp2")
        self.labelImgFileName = QtWidgets.QLabel(Dialog)
        self.labelImgFileName.setGeometry(QtCore.QRect(140, 190, 461, 16))
        self.labelImgFileName.setObjectName("labelImgFileName")
        self.graphicsViewImgPreview = QtWidgets.QGraphicsView(Dialog)
        self.graphicsViewImgPreview.setGeometry(QtCore.QRect(40, 260, 631, 421))
        self.graphicsViewImgPreview.setObjectName("graphicsViewImgPreview")
        self.labelHelp3 = QtWidgets.QLabel(Dialog)
        self.labelHelp3.setGeometry(QtCore.QRect(40, 230, 221, 16))
        self.labelHelp3.setObjectName("labelHelp3")
        self.labelStartProcess = QtWidgets.QLabel(Dialog)
        self.labelStartProcess.setGeometry(QtCore.QRect(150, 730, 161, 16))
        self.labelStartProcess.setObjectName("labelStartProcess")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ExifGPSLocationEmbed"))
        self.pushButtonStart.setText(_translate("Dialog", "Start"))
        self.pushButtonSelectJsonFile.setText(_translate("Dialog", "Open..."))
        self.pushButtonSelectImgFile.setText(_translate("Dialog", "Open..."))
        self.labelHelp1.setText(_translate("Dialog", "Select Location Json File:"))
        self.labelJsonFileName.setText(_translate("Dialog", "Not Selected!"))
        self.labelHelp2.setText(_translate("Dialog", "Select Image File:"))
        self.labelImgFileName.setText(_translate("Dialog", "Not Selected!"))
        self.labelHelp3.setText(_translate("Dialog", "Image Preview:"))
        self.labelStartProcess.setText(_translate("Dialog", "Click to start..."))
